---
- hosts: influx
  become: yes
  become_user: root
  become_method: su
  tasks:
  - name: Create Directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0775
    loop:
      - '/opt/senat'
      - '/opt/senat/distr'
      - '/opt/senat/service'
      - '/opt/senat/service/influxdb'
      - '/opt/senat/logs'
      - '/opt/senat/logs/service'
  - name: Disabling SELINUX
    ansible.builtin.lineinfile:
      path: /etc/selinux/config
      search_string: 'SELINUX=enforcing'
      line: SELINUX=disabled
      owner: root
      group: root
      mode: '0644'
  - name: Add servers to hosts file
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{ hostvars[item].server_ip }}  {{ hostvars[item].server_name }}"
      create: yes  
    with_items: "{{ groups['opensearch'] }}"
  - name: Disabling SELINUX
    ansible.builtin.shell: setenforce 0
  - name: Stop firewall
    ansible.builtin.service:
      name: firewalld
      state: stopped
  - name: Disable firewall
    ansible.builtin.service:
      name: firewalld
      enabled: false
  - name: Download Influx
    ansible.builtin.get_url:
      url: https://dl.influxdata.com/influxdb/releases/influxdb-1.8.0_linux_amd64.tar.gz
      dest: /opt/senat/distr/influxdb-1.8.0_linux_amd64.tar.gz
      mode: '0440'
  - name:  Unpacking Influx
    ansible.builtin.shell: cd /opt/senat/distr/ && tar -xzvf influxdb-1.8.0_linux_amd64.tar.gz
  - name:  Move Influx to target Directory
    ansible.builtin.shell: cd /opt/senat/distr/ && cp -r influxdb-1.8.0-1/* /opt/senat/service/influxdb
  - name:  Allow Influx binary to tart
    ansible.builtin.shell: chmod +x /opt/senat/service/influxd/usr/bin/influxd
  - name: Create Service for Influx
    template: 
      src: influx/influx.service.j2
      dest: /usr/lib/systemd/system/influx.service
  - name: Configure Influx    
    become: no
    shell: |
      sed -i 's/# retention-autocreate/retention-autocreate/' /opt/senat/service/influxdb/etc/influxdb/influxdb.conf
      sed -i 's/# max-values-per-tag/max-values-per-tag/' /opt/senat/service/influxdb/etc/influxdb/influxdb.conf
  - name: Start Influx
    ansible.builtin.service:
      name: influx
      state: started       
  - name: Enable service Influx
    ansible.builtin.service:
      name: influx
      enabled: yes 
  - name: Create and Tuning Senat database in Influx    
    become: no
    shell: |
      /opt/senat/service/influxdb/usr/bin/influx -execute "CREATE DATABASE senat_api_metrics"
      /opt/senat/service/influxdb/usr/bin/influx -database senat_api_metrics -execute "CREATE USER senat_user WITH PASSWORD 'senat_pass'"
      /opt/senat/service/influxdb/usr/bin/influx -database senat_api_metrics -execute "GRANT ALL PRIVILEGES TO senat_user"
      /opt/senat/service/influxdb/usr/bin/influx -database senat_api_metrics -execute 'ALTER RETENTION POLICY "autogen" ON "senat_api_metrics" DURATION 12w SHARD DURATION 168h DEFAULT'
      sed -i 's/# auth-enabled/auth-enabled/' /opt/senat/service/influxdb/etc/influxdb/influxdb.conf
      systemctl restart influx.service